[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/model"
  to = "/.netlify/functions/server"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/public/index.html"
  status = 200
  force = false

