[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
from = "/public/index.html"
to = "/"
status = 200
force = false
[[redirects]]
from = "/public/geometry/"
to = "/geometry/"
status = 200
force = false
[[redirects]]
from = "/public/img/"
to = "/img/"
status = 200
force = false
[[redirects]]
from = "/public/lib/"
to = "/lib/"
status = 200
force = false
[[redirects]]
from = "/public/style/"
to = "/style/"
status = 200
force = false
