[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/public/index.html"
  to = "/"
  status = 200
  ## force = false
  ## query = {path = ":path"}
  ## conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
